[package]
name = "eventline"
version = "0.7.2"
edition = "2024"
authors = ["Dustin Pilgrim <dustin.pilgrim1997@gmail.com>"]
description = "Structured journaling and scoped logging for Rust applications."
license = "MIT"
repository = "https://github.com/saltnpepper97/eventline"
readme = "README.md"
keywords = ["logging", "journal", "tracing", "scopes", "debugging"]
categories = ["development-tools::debugging", "development-tools::profiling"]
rust-version = "1.89"

[dependencies]
libc = "0.2.182"
parking_lot = "0.12.5"
serde = { version = "1.0.228", features = ["derive"] }

[features]
default = []
